# Generated by Django 3.2.3 on 2021-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_auto_20210705_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=100)),
                ('mail_departement', models.EmailField(max_length=100)),
                ('numero_departement', models.CharField(default='', max_length=80)),
                ('description_dept', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartementModel',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
