# Generated by Django 3.2.3 on 2021-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0005_departement_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='dept',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='dept',
            field=models.CharField(choices=[('GIT', 'GIT'), ('GC', 'GC'), ('GEM', 'GEM'), ('AERO', 'AERO')], default='GIT', max_length=100),
        ),
    ]
